server:
  port: 8081
    
spring:
  data:
    mongodb:
      authentication-database: admin
      database: moviedb
      username: superAdmin
      password: admin123
      port: 27017
  application:
    name: movie
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
